name: env
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-build
  - pip
  - python
  - setuptools
  - latexmk
  - tornado
  - git
  - pip:
    - setuptools
    - h5py
    - argparse
    - jupyterlab
    - tornado
