name: env
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-build
  - pip
  - python=3.6.9
  - setuptools
  - bedtools
  - bedops
  - samtools
  - cmake
  - numpy
  - pip:
    - setuptools
    - gnureadline
    - numpy
    - plotly
    - pandas
    - dash
    - dash-html-components
    - dash-core-components
    - dash-renderer
    - flask
    - flask_sqlalchemy
    - APScheduler
    - gunicorn
    - jupyter
    - jupyterlab
    - cmake
    - networkx
    - ipywidgets
    - Cython
#    - seaborn
    - pysam
    - myvariant
    - mygene
#    - weblogo
#    - h5py
#    - wand
#    - mechanize
#    - rst2pdf
    - argparse
    - python-louvain
#    - uuid
    - joblib
    - biopython
    - pyliftover
    - bx-python
    - MACS2
    - selene-sdk
