#!/bin/bash
# Viewing only for Euplotid, minimal image to run jupyter viewer
#
# Author: Diego Borges
# Date 04/05/17

FROM maxjiang/rpi-jupyter:datascience
MAINTAINER Diego Borges <dborgesr@mit.edu>

RUN apt-get update && apt-get upgrade && apt-get install git libmagickwand-dev

RUN pip3 install plotly myvariant mygene wand uuid biopython nbbrowserpdf networkx

#Update python packages
RUN pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U

# Configure jupyter
RUN sed -i "/c.NotebookApp.token/c c.NotebookApp.token = 'Euplotid'" /root/.jupyter/jupyter_notebook_config.py && \
     sed -i "/c.NotebookApp.iopub_data_rate_limit/c NotebookApp.iopub_data_rate_limit = '10000000'" /root/.jupyter/jupyter_notebook_config.py 

#Get Euplotid
RUN cd /root && git clone https://github.com/dborgesr/Euplotid.git 
WORKDIR /root/notebooks

RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

ENTRYPOINT ["/usr/bin/tini", "--"]

EXPOSE 8890
CMD ["jupyter", "notebook", "--allow-root", "--port=8890", "--no-browser", "--ip=0.0.0.0"]
