# Viewing only for Euplotid, minimal image to run jupyter viewer
#
# Author: Diego Borges
# Date 04/05/17

FROM resin/rpi-raspbian:jessie
MAINTAINER Diego Borges <dborgesr@mit.edu>

WORKDIR /root

# Install packages necessary for compiling python
RUN apt-get update && apt-get upgrade && apt-get install -y \
        build-essential \
        libncursesw5-dev \
        software-properties-common \
        libgdbm-dev \
        libzmq3-dev \
        libc6-dev \
        zlib1g-dev \
        libsqlite3-dev \
        tk-dev \
        libssl-dev \
        openssl \
        libbz2-dev \
        python-matplotlib \
        python-scipy \
        python-dev \
        python-pip \
        libncurses5-dev \
        git

# Update pip and install jupyter
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install readline jupyter plotly myvariant mygene plotly
RUN pip install notebook ipywidgets wand uuid biopython nbbrowserpdf

#Get Euplotid
RUN cd /root && git clone https://github.com/dborgesr/Euplotid.git 

# Configure jupyter
RUN jupyter notebook --generate-config --allow-root
RUN sed -i "/c.NotebookApp.open_browser/c c.NotebookApp.open_browser = False" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.ip/c c.NotebookApp.ip = '*'" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.notebook_dir/c c.NotebookApp.notebook_dir = '/root/Euplotid'" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.token/c c.NotebookApp.token = 'Euplotid'" /root/.jupyter/jupyter_notebook_config.py

VOLUME /root

ENV TINI_VERSION v0.14.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /root/tini
RUN chmod 755 /root/tini
ENTRYPOINT ["sudo","/root/tini", "--"]

EXPOSE 8891
CMD ["jupyter", "notebook", "--port=8891", "--no-browser", "--ip=0.0.0.0"]

